### ISSUE TITLE
API para autenticar usuário

### ISSUE THREAD

**Issue by HugoLnx** [gberger/PES-3#13]
API para autenticar admin e restringir rotas de acordo com o permissionamento do mesmo.

**Comment by gberger** [comment]
Será que ele considera isso importante? 😅

**Comment by HugoLnx** [comment]
Haha Acho que pra amanhã nem é importante pq a gente não precisa disso pra demonstrar. Mas eu devo implementar mesmo assim se sobrar tempo por que estou querendo minimizar o quanto teremos que mexer nisso dps dessa apresentação de amanhã, prefiro até que não tenhamos que mexer.
